[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true
  # Replace "your-backend-url.com" with your actual backend URL when deployed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200