[build]
  base = "."
  publish = "client/dist"
  command = "cd client && npm run build"
  
[build.environment]
  NODE_VERSION = "20"

# Handle SPA routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200